Update Code STT APP with Parameter
ibm-build-lab/Watson-Speech pull request #3
Opened 2022-10-18 14:26 UTC by Abhilasha-Mangal

2022-10-18 22:41 UTC, htalukderibm requested changes

2022-10-18 22:41 UTC, hitalukder commented on STTApplication/src/main/java/com/build/labs/controller/STTController.java
> +				List time_stamp = alternative.getTimestamps();
Can you please make List<> generic?

2022-10-18 22:41 UTC, hitalukder commented on STTApplication/src/main/java/com/build/labs/feignclient/SSTServingClient.java
> +public final String STT_REST_MAPPING2 = "/speech-to-text/api/v1/recognize?model=en-US_Telephony";
We can probably use the same variable either STT_REST_MAPPING1 or STT_REST_MAPPING2

2022-10-18 22:41 UTC, hitalukder commented on STTApplication/src/main/java/com/build/labs/controller/STTController.java
> +		InputStream input1 = new ClassPathResource("static/audio/" + filename).getInputStream();
Input and input1 are same instance

2022-10-18 22:48 UTC, htalukderibm requested changes

2022-10-18 22:48 UTC, htalukderibm commented on STTApplication/src/main/java/com/build/labs/controller/STTController.java
> +		if (filename.startsWith("samples")) {
Can you create your a separate method instead hardcoded filenames? Otherwise in future if anybody wants to change there will be a lot of work.

2022-10-18 22:48 UTC, htalukderibm commented on STTApplication/src/main/java/com/build/labs/services/STTService.java
> +		if(fileName.contains("back"))
if we can avoid hardcoded file it would be great

2022-10-19 10:46 UTC, Abhilasha-Mangal commented on STTApplication/src/main/java/com/build/labs/controller/STTController.java
> +		InputStream input1 = new ClassPathResource("static/audio/" + filename).getInputStream();
Yes, but after passing the same data to one service we can't pass the same input to the service. It is showing data is not available. So here created another instance of data to pass the service.

2022-10-19 10:48 UTC, Abhilasha-Mangal commented on STTApplication/src/main/java/com/build/labs/services/STTService.java
> +		if(fileName.contains("back"))
Actually here we are showing the use case & all files do not have the same functionality that's why I used the files by which we can show the parameter use case.

2022-10-19 10:54 UTC, Abhilasha-Mangal commented on STTApplication/src/main/java/com/build/labs/controller/STTController.java
> +				List time_stamp = alternative.getTimestamps();
No, Actually both JSON outputs have different values.

2022-10-19 10:56 UTC, Abhilasha-Mangal commented on STTApplication/src/main/java/com/build/labs/feignclient/SSTServingClient.java
> +public final String STT_REST_MAPPING2 = "/speech-to-text/api/v1/recognize?model=en-US_Telephony";
Yes, I updated it again with one. Previously I was facing issues with multiple requests. For testing one I created different one.

2022-10-19 19:55 UTC, htalukderibm approved these changes

2022-10-19 19:55 UTC, merged